config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users, only: [ :new, :create, :show ]
  resources :passwords, param: :token
  resources :events do
    resources :runners
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "homes#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/donator.rb
class Donator < ApplicationRecord
  belongs_to :runner
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_organisations
  has_many :runners, -> {readonly}, through: :event_organisations
  has_rich_text :description
  has_many :organisations, -> {readonly}, through: :event_organisations, dependent: :destroy
  validate :check_no_runners

  def check_no_runners
    if runners.any?
      puts("lol")
      errors.add(:base, "🚨 There are runners signed up for the event you try to update. 🚨")
    end
  end

end

app/models/event_organisation.rb
class EventOrganisation < ApplicationRecord
  belongs_to :event
  belongs_to :organisation
  delegate :name, to: :organisation
  has_many :runners, dependent: :restrict_with_error
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :event_organisations
  has_many :runners, through: :event_organisations
  has_one_attached :image
end

app/models/runner.rb
class Runner < ApplicationRecord
  belongs_to :user
  belongs_to :event_organisation
  has_many :donators
  has_one :event, through: :event_organisation
  has_one :organisation, through: :event_organisation
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :runners
  has_many :donators
  has_one_attached :profile_picture

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def runner_for?(event)
    runners.where(event_organisation: event.event_organisations).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  allow_unauthenticated_access only: [ :show ]
  def new
    @event = Event.new
  end

  def create
    parameters = params.expect(event: {})
    @event = Event.create! parameters
    redirect_to @event
  end

  def show
    @event = Event.find(params.expect(:id))
  end

  def edit
    @event = Event.find(params.expect(:id))
  end

  def update
    @event = Event.find(params.expect(:id))
    if @event.update params.expect(event: [:name, :date, :round_distance_in_meters, :description, organisation_ids: []])
      redirect_to @event 
    else
      render(:edit, status: :unprocessable_content)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  allow_unauthenticated_access only: [ :show ]
  def show
    @events = Event.all
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController< ApplicationController
  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.create! params.expect(organisation: [:name, :homepage, :image])
    redirect_to @organisation
  end

  def show
    @organisation = Organisation.find(params.expect(:id))
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  def new
    @event = Event.find params.expect(:event_id)
    @runner = Current.user.runners.new
  end
  def create
    @event = Event.find params.expect(:event_id)
    runners_params = params.expect(runner: [:rounds, :minutes, :seconds, :event_organisation_id])
    runners_params[:time_per_round_in_seconds] = runners_params.delete(:minutes).to_i.minutes + runners_params.delete(:seconds).to_i
    @runner = Current.user.runners.create! event: @event, **runners_params 
    redirect_to [@event, @runner]
  end
  def show
    @runner = Runner.find params.expect(:id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: [ :new, :create ]
  def new
    @user = User.new
  end

  def create
    parameters = params.expect(user: [:name, :email_address, :password, :password_confirmation])
    @user = User.create! parameters
    start_new_session_for @user
    redirect_to after_authentication_url
  end

  def show
    @user = User.find(params.expect(:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/events/_form.html.erb
<%=form_with model: event do |form| %>
  <%=form.text_field :name %>
  <%=form.datetime_field :date %>
  <%=form.number_field :round_distance_in_meters %>
  <%=form.rich_textarea :description %>
  <%=form.collection_checkboxes :organisation_ids, Organisation.all, :id, :name %>
  <%=form.object.errors.full_messages %>
  <%=form.submit %>
<% end %>

app/views/events/edit.html.erb
<%=render "form", event: @event%>

app/views/events/new.html.erb
<%=form_with model: @event do |form| %>
  <%=form.text_field :name %>
  <%=form.datetime_field :date %>
  <%=form.number_field :round_distance_in_meters %>
  <%=form.rich_textarea :description %>
  <%=form.submit %>
<% end %>

app/views/events/show.html.erb
<%=@event.name%><br>
<%=@event.date%><br>
<%=@event.round_distance_in_meters%><br>
<%=@event.description%><br>
<% if authenticated? %>
  <% if runner = Current.user.runner_for?(@event) %>
    <%=turbo_frame_tag "runner", src: event_runner_path(@event, runner) %>
  <% else %>
    <%=turbo_frame_tag "runner", src: new_event_runner_path(@event) %>
  <% end %>
<% else %>
  Please log in or create a new account to sign up for this event.
<% end %>

app/views/homes/show.html.erb
<h2 class="text-2xl">Events</h2>
<%@events.each do |event| %>
  <%=link_to event.name, event%><br>
<%end%>
<% if authenticated? %>
  <%=link_to "Create new Event!", new_event_path%><br>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cool Runnings" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-50">
    <nav class="fixed top-0 left-0 w-full bg-white shadow px-8 py-4 flex items-center justify-between z-50">
      <div class="text-lg font-semibold text-gray-800">
        <%=link_to "Cool Runnings", root_path%>
      </div>

      <div class="flex items-center space-x-4">
        <% if authenticated? %>
          <div class="text-lg text-gray-800">
            Hello, <%= Current.user.name %> 👋
          </div>
          <%=button_to "Log out", session_path, method: :delete,
              class: "text-red-600 hover:text-red-800 font-medium" %>
        <% else %>
          <div class="text-lg text-gray-800">
            Welcome 👋
          </div>
          <%= link_to "Log in", new_session_path, 
              class: "text-blue-600 hover:text-blue-800 font-medium" %>
          <%= link_to "Sign up", new_user_path, 
              class: "text-green-600 hover:text-green-800 font-medium" %>
        <% end %>
      </div>
    </nav>
    <main class="pt-20 px-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/runners/new.html.erb
<%=turbo_frame_tag "runner" do %>
  <%=form_with model: [@event, @runner] do |form| %>
    <%=form.label :rounds %>:
    <%=form.number_field :rounds %><br>
    <%=form.label :minutes %>:
    <%=form.number_field :minutes %><br>
    <%=form.label :seconds %>:
    <%=form.number_field :seconds %><br>
    <%=form.label :event_organisation_id %>:
    <%=form.collection_select :event_organisation_id, @event.event_organisations, :id, :name, prompt: true %><br>
    <%=form.submit "Sign up for event"%>
  <% end %>
<% end %>

app/views/runners/show.html.erb
<%=turbo_frame_tag "runner" do %>
  <h1 class="text-2xl">"You are signed up for this event!"</h1>
  Rounds:
  <%=@runner.rounds%><br>
  Time per round:
  <% seconds = @runner.time_per_round_in_seconds %>
  <% minutes = seconds / 60 %>
  <% remaining_seconds = seconds % 60 %>
  <%=minutes%> min. <%=remaining_seconds%> sec. 
<% end %>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if alert = flash[:alert] %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <% if notice = flash[:notice] %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Sign in</h1>

  <%= form_with model: @user, class: "contents" do |form| %>
    <div class="my-5">
      <%= form.text_field :name, required: true, autofocus: true, autocomplete: "name", placeholder: "Enter your name", class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.email_field :email_address, required: true, autocomplete: "username", placeholder: "Enter your email address", class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.password_field :password, required: true, autocomplete: "new-password", placeholder: "Enter your password", maxlength: 72, class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.password_field :password_confirmation, required: true, autocomplete: "new-password", placeholder: "Confirm your password", maxlength: 72, class: "block shadow-sm rounded-md border border-gray-400 focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
      <div class="inline">
        <%= form.submit "Sign up", class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
      </div>
    </div>
  <% end %>
</div>